### ISSUE TITLE
Fail to load model in test_regression_model

### ISSUE THREAD

**Issue by akionakamura** [udacity/nd0821-c2-build-model-workflow-starter#8]
In the `test_regression_model` component, I get and error when trying to load the model:
```

2021-09-28 00:27:21,210 Downloading artifacts
2021-09-28 00:27:24,128 Loading model and performing inference on test set
Traceback (most recent call last):
  File "/opt/loggi/nd0821-ml-pipeline/src/test_regression_model/run.py", line 73, in <module>
    go(args)
  File "/opt/loggi/nd0821-ml-pipeline/src/test_regression_model/run.py", line 37, in go
    sk_pipe = mlflow.sklearn.load_model(model_local_path)
  File "/home/akio/miniconda3/envs/mlflow-d4cd2edbe762204ae630d5e343c25b496b164e3c/lib/python3.9/site-packages/mlflow/sklearn/__init__.py", line 471, in load_model
    local_model_path = _download_artifact_from_uri(artifact_uri=model_uri)
  File "/home/akio/miniconda3/envs/mlflow-d4cd2edbe762204ae630d5e343c25b496b164e3c/lib/python3.9/site-packages/mlflow/tracking/artifact_utils.py", line 83, in _download_artifact_from_uri
    return get_artifact_repository(artifact_uri=root_uri).download_artifacts(
  File "/home/akio/miniconda3/envs/mlflow-d4cd2edbe762204ae630d5e343c25b496b164e3c/lib/python3.9/site-packages/mlflow/store/artifact/local_artifact_repo.py", line 79, in download_artifacts
    raise IOError("No such file or directory: '{}'".format(local_artifact_path))
OSError: No such file or directory: './artifacts/random_forest_export%3Av3'
```

Executing it locally, I've find out that there is a problem in the usage of the path `./artifacts/random_forest_export:v3`, where it actually tries to load `./artifacts/random_forest_export%3Av3`.

**Comment by gaceladri** [comment]
The same issue here. Hardcoding the paths doesn't work either.

**Comment by gaceladri** [comment]
solution: model_local_path = run.use_artifact(args.mlflow_model).download('./artifacts/random_forest_export_v{your_version_hardcoded}')

**Comment by marcusholmgren** [comment]
This can also be solve by upgrading version `mlflow=1.17.0` in condo.yml. Then your MLflow pipeline step for `test_regression_model` have to point to your local components folder.

**Comment by ronny-udacity** [comment]
PR #12
